name: c2sanilist
description: Anime browser built with AniList APIs

publish_to: "none"
version: 2.0.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  # Networking
  http: ^0.13.4

  # UI
  google_fonts: ^2.3.1

  # Miscellaneous
  meta: ^1.7.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
