name: c2sanilist
description: Anime browser built with AniList APIs

publish_to: "none"
version: 2.0.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  # Networking + JSON serialization/deserialization annotations
  http: ^0.13.4
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

  # UI
  google_fonts: ^2.3.1

  # Miscellaneous
  meta: ^1.7.0
  equatable: ^2.0.3
  loggy: ^2.0.1+1

dev_dependencies:
  # Launcher icons
  flutter_launcher_icons: ^0.9.2

  # Linter
  flutter_lints: ^1.0.4

  # Build runner
  build_runner: ^2.1.8

  # JSON serialization/deserialization
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/app_icon.png
  image_path_android: assets/app_icon.png
  image_path_ios: assets/app_icon_ios.png

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/app_icon_ios.png
